#!/usr/bin/env python3
"""
Pre-render the boat fleet into the raw HTML so search engines and AI crawlers
(which read static HTML and do NOT execute JavaScript) can see the full fleet.

Source of truth: public/content/boats.json (edited via Pages CMS).
The existing JavaScript on each page still runs for real visitors — it re-renders
the grid from the freshest JSON on load — so this pre-render is a crawler-facing
+ no-JS fallback that mirrors the JS output.

This runs automatically on every Netlify deploy (see netlify.toml `command`),
including when the CMS commits boats.json, so the static HTML never drifts.

Safe by design: any error is caught and the build continues untouched (exit 0),
so a problem here can never block a deploy.

Run manually:  python3 scripts/build-boats.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOATS_JSON = os.path.join(ROOT, "public", "content", "boats.json")

START = "<!-- BOATS:AUTO:START — generated by scripts/build-boats.py from content/boats.json. Do not edit between these markers. -->"
END = "<!-- BOATS:AUTO:END -->"


def esc(value):
    """Mirror of the pages' escapeHtml()."""
    s = "" if value is None else str(value)
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;").replace("'", "&#039;"))


def to_int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def num(value):
    """Mirror of JS Number.toLocaleString('en-US') for integers."""
    return f"{value:,}"


def slugify(name):
    """Mirror of the JS slug chain (ASCII \\w, as JS uses no unicode flag)."""
    s = (name or "").lower()
    s = re.sub(r"[^\w\s-]", "", s, flags=re.ASCII)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    s = re.sub(r"^-+|-+$", "", s)
    return s


def homepage_tagline(guests, overnight):
    if overnight:
        return "Luxury Overnight Experience"
    if guests >= 12:
        return "Perfect for Large Groups"
    if guests >= 10:
        return "Great for Family & Friends"
    if guests >= 7:
        return "Perfect for Small Groups"
    return "Ideal for Couples"


def render_homepage(boat):
    """Port of renderHomepageBoat() in index.html."""
    name = esc(boat.get("name"))
    name_js = (boat.get("name") or "").replace("'", "\\'")
    image = esc(boat.get("image") or "/assets/img/RivaArgo90.jpeg")
    guests = to_int(boat.get("guests"))
    overnight = bool(boat.get("overnight"))
    lowest = (to_int(boat.get("price_may")) or to_int(boat.get("price_october"))
              or to_int(boat.get("price_june")) or to_int(boat.get("price_september")))
    price_label = ("From €" + num(lowest) + "/day") if lowest > 0 else "Price on request"
    tagline = homepage_tagline(guests, overnight)
    capacity = "Overnight Stay" if overnight else ("Up to " + str(guests) + " guests")
    slug = slugify(boat.get("name"))
    return (
        f'<div class="col-md-4"><div class="boat-item"><div class="image-container">'
        f'<img src="{image}" alt="{name}" loading="lazy"><div class="image-overlay">'
        f'<span class="boat-type">{tagline}</span></div></div><div class="boat-content">'
        f'<div class="boat-name">{name}</div><div class="key-features">'
        f'<span class="price-tag">{price_label}</span><span class="capacity">{capacity}</span></div>'
        f'<div class="boat-actions"><button class="enquiry-btn" onclick="openInquiryForm(\'{name_js}\')">BOOK NOW</button>'
        f'<a href="/boat/{slug}/" class="view-details">View Details</a></div></div></div></div>'
    )


def _price_cell(month, value):
    cls = "" if value > 0 else " no-price"
    text = ("€" + num(value)) if value > 0 else "—"
    return (f'<div class="price-col"><div class="price-month">{month}</div>'
            f'<div class="price-amount{cls}">{text}</div></div>')


def render_fleet(boat):
    """Port of renderBoatCard() in yacht-rental.html."""
    name = esc(boat.get("name"))
    image = esc(boat.get("image") or "/assets/img/RivaArgo90.jpeg")
    image_position = esc(boat.get("image_position") or "center")
    length = esc(boat.get("length") or "")
    guests = to_int(boat.get("guests"))
    btype = esc(boat.get("type") or "motor")
    if boat.get("overnight"):
        captain = '<span class="spec-item"><i class="fas fa-bed"></i> Overnight</span>'
    elif boat.get("captain_included") is not False:
        captain = '<span class="spec-item"><i class="fas fa-user-shield"></i> Captain incl.</span>'
    else:
        captain = ""
    p_may = to_int(boat.get("price_may"))
    p_jun = to_int(boat.get("price_june"))
    p_jul = to_int(boat.get("price_july"))
    p_aug = to_int(boat.get("price_august"))
    p_sep = to_int(boat.get("price_september"))
    p_oct = to_int(boat.get("price_october"))
    filter_price = p_may or p_oct or p_jun or p_sep or p_jul or p_aug or 0
    slug = slugify(boat.get("name"))
    cells = (_price_cell("May", p_may) + _price_cell("Jun", p_jun) + _price_cell("Jul", p_jul)
             + _price_cell("Aug", p_aug) + _price_cell("Sep", p_sep) + _price_cell("Oct", p_oct))
    return (
        f'<div class="card-wrapper" data-type="{btype}" data-guests="{guests}" data-price="{filter_price}">'
        f'<div class="yacht-card"><div class="yacht-image-wrapper">'
        f'<img class="boat-image" src="{image}" alt="{name} boat rental Ibiza" loading="lazy" style="object-position: {image_position};">'
        f'<button class="favorite-btn" aria-label="Add to favorites"><i class="far fa-heart"></i></button></div>'
        f'<div class="yacht-content"><div class="card-header"><h3 class="yacht-name">{name}</h3>'
        f'<div class="specs-row"><span class="spec-item"><i class="fas fa-ruler-combined"></i> {length}</span>'
        f'<span class="spec-item"><i class="fas fa-users"></i> {guests} guests</span>{captain}</div></div>'
        f'<div class="pricing-grid-h">{cells}</div>'
        f'<div class="action-buttons"><a href="/boat/{slug}/" class="btn-view">View Details</a>'
        f'<button class="btn-inquire" data-boat="{name}">Book Now</button></div></div></div></div>'
    )


def inject(rel_path, cards_html):
    path = os.path.join(ROOT, rel_path)
    with open(path, encoding="utf-8") as f:
        html = f.read()
    if START not in html or END not in html:
        print(f"  ! markers not found in {rel_path} — skipped (run once with markers in place)")
        return False
    block = START + "\n" + cards_html + "\n" + END
    new_html = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _m: block, html, flags=re.DOTALL)
    if new_html != html:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_html)
        print(f"  ✓ {rel_path} updated")
    else:
        print(f"  = {rel_path} already current")
    return True


def main():
    with open(BOATS_JSON, encoding="utf-8") as f:
        data = json.load(f)
    boats = [b for b in (data.get("boats") or []) if b.get("published") is not False]
    print(f"Pre-rendering {len(boats)} published boats…")

    home_cards = "\n".join(render_homepage(b) for b in boats)
    fleet_cards = "\n".join(render_fleet(b) for b in boats)

    inject("public/index.html", home_cards)
    inject("public/yacht-rental.html", fleet_cards)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # never block a deploy
        print(f"WARN: boat pre-render skipped ({exc})", file=sys.stderr)
    sys.exit(0)
